### ISSUE TITLE
Allow bare elements at root level

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/archie#40]
Currently item elements must be defined in the long form at the root level:
```yaml
model:
  elements:
    - name: hello
```
It would be nice to be able to use the short form:
```yaml
model:
  elements:
    - hello
```
