### ISSUE TITLE
Document interfaces

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/archie#7]
When two items connect via multiple sub-items it can be easy to lose track of the number of connections that must be supported through that interface.

In the future it would be nice to have some way of enumerating the different connections contained within an interface.

**Comment by briggySmalls** [comment]
Note that this might ruin the plan to just have a JSON to JSON core?

I'm not sure. Perhaps not, perhaps an interface view would look like:
```yaml
elements:
  - name: user
    kind: actor
  - name: sound-system
    children:
      - name: speaker
        children:
          - cable
      - name: amplifier
        children:
          - audio out connector
associations:
  - source: sound-system/amplifier/amplifier
    destination: sound-system/amplifier/audio out connector
  - source: sound-system/amplifier/audio out connector
```
